name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - run: dart analyze --fatal-infos lib test tool
      - run: dart test
      - run: dart pub get
        working-directory: example
        if: ${{ matrix.sdk == 'stable' }}
      - run: dart tool/check_example.dart
        if: ${{ matrix.sdk == 'stable' }}
      - run: dart pub publish --dry-run
        if: ${{ matrix.sdk == 'stable' }}
